### ISSUE TITLE
Year 4 Season 1 Operators - Gridlock & Mozzie

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#1]
- Add new icons from https://marcopixel.eu/r6-operatoricons/
- Add operators to the graph
- Add any counter relationships for these operators
- Open a new issue for further relationship refinement after the operators have been released for a few days

**Comment by BurkusCat** [comment]
This issue cannot be completed yet.

**Comment by BurkusCat** [comment]
https://www.reddit.com/r/Rainbow6/comments/ar2o8o/gridlockmozzie_highresolution_operator_icons/

**Comment by lynx-the-cat** [comment]
I was looking to contribute to this project. I figured I would start with the oldest issues and work my way towards the newer ones. This issue seems to have been resolved and should be closed. 

The SVG files for both Gridlock and Mozzie exist in [/src/main/images/svg](https://github.com/BurkusCat/r6-operator-counters/tree/master/src/main/images/svg) 
Counters have also been added to [r6OperatorsCounters.json](https://github.com/BurkusCat/r6-operator-counters/blob/master/src/main/json/r6OperatorCounters.json)

It looks like this was handled in PR #123 

Note: I'm not a R6 Siege player, so won't be able to provide input on the data being provided itself. But as a game, I understand the value of tools like this and would like to help refine and expand upon this tool.

**Comment by BurkusCat** [comment]
Thanks @lynx-the-cat ! You are very welcome to contribute to the project.

The project hasn't been too active in the past few months because we've put a hold on adding new relationships to the graph (apart from brand new character releases). The reason we did this is because the performance of the site is really bad. The framerate is very low when using it and it feels sluggish. This gets worse the more relationships we add to the graph.

Feel free to look at any maintenance tasks (improving the development environment etc.) or any enhancement tasks (i.e. making the site easier to read, adding more ways to filter the data etc.). Any ideas for new issues are welcome too!

The biggest area of need are the performance issues. It would be awesome to improve the performance of the site as it would make so many of the other tickets easier to work on (its hard to add new data when it ends up making the site slower and slower).

Feel free to send me any questions if you would like to contribute to the project! :)
