### ISSUE TITLE
Latest merge

### ISSUE THREAD

**Issue by CrayCrayDecay** [BurkusCat/r6-operator-counters#127]
The latest merge appears to have broken the website CSS formatting.

**Comment by CrayCrayDecay** [comment]
![r6-counterissue](https://user-images.githubusercontent.com/7763128/57387815-44725780-7174-11e9-91c1-aa800f76aac7.png)

**Comment by BurkusCat** [comment]
If I get a chance tonight I'll try put together a branch with a revert commit.

**Comment by abuDarda97** [comment]
Damn sorry about that guys, the website worked fine on my local machine. I am not sure why it's doing that now.

**Comment by BurkusCat** [comment]
No worries, it'll be back to normal again soon :) The "release" task vs the normal debug gulp task are a bit different I think. The release of the site uses "gulp build" whereas when debugging I'd normally use just "gulp". The "gulp build" task runs slightly differently I believe because you don't need things like live reload etc.
